import type { Backend } from "@/backend";
import type {
  Category,
  Product,
  ProductDetails,
  ProductId,
} from "@/types/product";

/**
 * Raw product shape as returned by the generated bindings, where
 * `priceInPaise` is a `bigint` (Candid `Nat`). The adapter below normalizes it
 * to a plain `number` so the rest of the app never mixes BigInt and Number.
 */
interface RawProduct extends Omit<Product, "priceInPaise"> {
  priceInPaise?: bigint | null;
}

/**
 * Typed access to the product API on the generated backend actor.
 *
 * The bindgen output is regenerated by the contract-check task; until then the
 * generated `Backend` interface only declares the authorization surface. This
 * module narrows the actor to the product methods the backend mixin exposes
 * (`mixins/products-api.mo`) so the rest of the app codes against one typed
 * boundary instead of casting at every call site.
 *
 * The generated binding types `PriceInPaise` as `bigint`; this adapter converts
 * it to a `number` on read and back to `bigint` on write so every consumer sees
 * the plain-number `Product` shape declared in `types/product.ts`.
 */
interface ProductsApi {
  listProducts(): Promise<Product[]>;
  getProduct(id: ProductId): Promise<Product | null>;
  setProductPrice(id: ProductId, priceInPaise: number | null): Promise<void>;
  setProductAvailability(id: ProductId, available: boolean): Promise<void>;
  updateProductDetails(id: ProductId, details: ProductDetails): Promise<void>;
  setProductImage(id: ProductId, imageKey: string): Promise<void>;
  seedProducts(): Promise<void>;
}

/** Convert a bigint paise amount from the bindings to a plain number. */
function normalizePrice(priceInPaise?: bigint | null): number | undefined {
  if (priceInPaise == null) return undefined;
  return Number(priceInPaise);
}

/** Normalize one raw product row to the frontend `Product` shape. */
function normalizeProduct(raw: RawProduct): Product {
  return { ...raw, priceInPaise: normalizePrice(raw.priceInPaise) };
}

/** Narrow the generated actor to the product API surface. */
export function productsApi(actor: Backend): ProductsApi {
  const raw = actor as unknown as {
    listProducts(): Promise<RawProduct[]>;
    getProduct(id: ProductId): Promise<RawProduct | null>;
    setProductPrice(id: ProductId, priceInPaise: bigint | null): Promise<void>;
    setProductAvailability(id: ProductId, available: boolean): Promise<void>;
    updateProductDetails(id: ProductId, details: ProductDetails): Promise<void>;
    setProductImage(id: ProductId, imageKey: string): Promise<void>;
    seedProducts(): Promise<void>;
  };

  return {
    async listProducts() {
      const products = await raw.listProducts();
      return products.map(normalizeProduct);
    },
    async getProduct(id) {
      const product = await raw.getProduct(id);
      return product ? normalizeProduct(product) : null;
    },
    setProductPrice(id, priceInPaise) {
      return raw.setProductPrice(
        id,
        priceInPaise == null ? null : BigInt(Math.round(priceInPaise)),
      );
    },
    setProductAvailability: (id, available) =>
      raw.setProductAvailability(id, available),
    updateProductDetails: (id, details) =>
      raw.updateProductDetails(id, details),
    setProductImage: (id, imageKey) => raw.setProductImage(id, imageKey),
    seedProducts: () => raw.seedProducts(),
  };
}

/** Public URL for a product image stored in object storage. */
export function productImageUrl(imageKey: string): string {
  if (!imageKey) return "/assets/images/placeholder.svg";
  if (imageKey.startsWith("/") || imageKey.startsWith("http")) return imageKey;
  return `/assets/products/${imageKey}`;
}

/** Sort products by their explicit sortOrder, then newest first. */
export function sortProducts(products: Product[]): Product[] {
  return [...products].sort((a, b) => {
    if (a.sortOrder !== b.sortOrder) return a.sortOrder - b.sortOrder;
    return Number(b.createdAt - a.createdAt);
  });
}

/** Case-insensitive name/description search. */
export function matchesSearch(product: Product, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return (
    product.name.toLowerCase().includes(q) ||
    product.description.toLowerCase().includes(q)
  );
}

/** Filter by category, or return all when no category is selected. */
export function filterByCategory(
  products: Product[],
  category: Category | null,
): Product[] {
  if (!category) return products;
  return products.filter((product) => product.category === category);
}
