/**
 * Shared product types mirroring the backend `types/products.mo` contract.
 *
 * The backend returns `Category` as a Candid variant and `priceInPaise` as an
 * optional `Nat`. The generated bindings are regenerated by the contract-check
 * task; these frontend types are the stable shape the UI codes against.
 */

/** Fixed set of store categories, matching the backend variant tags. */
export type Category =
  | "hairFlowers"
  | "hairBows"
  | "braidedAccessories"
  | "beaniesAndHats"
  | "hairClips"
  | "hairstyleLooks";

/** Stable identifier for a product row. */
export type ProductId = string;

/** Public product view returned across the API boundary. */
export interface Product {
  id: ProductId;
  name: string;
  category: Category;
  description: string;
  imageKey: string;
  /** Absent means "Price on request". */
  priceInPaise?: number;
  available: boolean;
  sortOrder: number;
  /** Unix timestamp in nanoseconds. */
  createdAt: bigint;
}

/** Input for creating/updating product details. */
export interface ProductDetails {
  name: string;
  category: Category;
  description: string;
}
