/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ProductId = IDL.Text;
export const Timestamp = IDL.Int;
export const PriceInPaise = IDL.Nat;
export const Category = IDL.Variant({
  'braidedAccessories' : IDL.Null,
  'beaniesAndHats' : IDL.Null,
  'hairBows' : IDL.Null,
  'hairstyleLooks' : IDL.Null,
  'hairClips' : IDL.Null,
  'hairFlowers' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'priceInPaise' : IDL.Opt(PriceInPaise),
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageKey' : IDL.Text,
  'category' : Category,
});
export const ProductDetails = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'setProductAvailability' : IDL.Func([ProductId, IDL.Bool], [], []),
  'setProductImage' : IDL.Func([ProductId, IDL.Text], [], []),
  'setProductPrice' : IDL.Func([ProductId, IDL.Opt(PriceInPaise)], [], []),
  'updateProductDetails' : IDL.Func([ProductId, ProductDetails], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ProductId = IDL.Text;
  const Timestamp = IDL.Int;
  const PriceInPaise = IDL.Nat;
  const Category = IDL.Variant({
    'braidedAccessories' : IDL.Null,
    'beaniesAndHats' : IDL.Null,
    'hairBows' : IDL.Null,
    'hairstyleLooks' : IDL.Null,
    'hairClips' : IDL.Null,
    'hairFlowers' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'priceInPaise' : IDL.Opt(PriceInPaise),
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageKey' : IDL.Text,
    'category' : Category,
  });
  const ProductDetails = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'setProductAvailability' : IDL.Func([ProductId, IDL.Bool], [], []),
    'setProductImage' : IDL.Func([ProductId, IDL.Text], [], []),
    'setProductPrice' : IDL.Func([ProductId, IDL.Opt(PriceInPaise)], [], []),
    'updateProductDetails' : IDL.Func([ProductId, ProductDetails], [], []),
  });
};

export const init = ({ IDL }) => { return []; };